version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"  # Expose the FastAPI app on port 8000
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Use the custom Nginx config
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - fastapi
    networks:
      - backend

networks:
  backend:
    driver: bridge