name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no vall@52.35.34.186 << 'EOF'
            set -e
            cd /home/vall/fastapi-book-project
            echo "Fetching latest code..."
            git fetch origin main
            echo "Resetting to origin/main..."
            git reset --hard origin/main
            echo "Stopping existing containers..."
            docker-compose down
            echo "Rebuilding and starting new containers..."
            docker-compose up -d --build
          EOF

      - name: Verify Containers
        run: |
          ssh -o StrictHostKeyChecking=no vall@52.35.34.186 << 'EOF'
            set -e
            echo "Verifying containers are running..."
            docker ps --filter "name=fastapi" --format "{{.Status}}" | grep -q "Up"
            docker ps --filter "name=nginx" --format "{{.Status}}" | grep -q "Up"
            echo "Containers are running!"
          EOF
